### ISSUE TITLE
Current Language is null even if it has been set

### ISSUE THREAD

**Issue by Abdelkrim** [newearthmartin/weebly-tools#1]
Hi Martin, I have followed your documentation [1] but the current lang remains null. For that reason, the menu isn't present.

Do you have any hint for me?

Thank you for your help

[1] http://blessingsweb.weebly.com/weebly-multilanguage.html

## Logs on the browser

see http://www.amia-systems.com

```
Language: en
languages-all.js:56 hiding menus for .wsite-menu-default
languages-all.js:87 MENU: amia systems - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: about us - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: publications - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: business process - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: videos - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: simogga ld - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: download simogga - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: system requirements - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: case study - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: customers - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: partners - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: contact us - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: urgent enquiries - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: legal - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: privacy policy - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: terms of use - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: copyright policy - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: amia systeme - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: simogga ld - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: kontakt - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: politik - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: datenschutzrichtlinien - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: nutzungsbedingungen - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: urheberrechtspolitik - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: amia systemes - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
languages-all.js:87 MENU: simogga ld - current lang: null - HIDE
languages-all.js:88 not in langs - not in all_langs
```

**Comment by newearthmartin** [comment]
The problem is in your langs definition
you are saying that the page name is 'home en' but it actually is 'amia
systems', and same for the other languages

take care!

On Wed, Apr 8, 2015 at 9:23 AM, Abdelkrim from Brussels <
notifications@github.com> wrote:

> Hi Martin, I have followed your documentation [1] but the current lang
> remains null. For that reason, the menu isn't present.
>
> Do you have any hint for me?
>
> Thank you for your help
>
> [1] http://blessingsweb.weebly.com/weebly-multilanguage.html
> Logs on the browser
>
> see http://www.amia-systems.com
>
> Language: en
> languages-all.js:56 hiding menus for .wsite-menu-default
> languages-all.js:87 MENU: amia systems - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: about us - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: publications - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: business process - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: videos - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: simogga ld - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: download simogga - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: system requirements - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: case study - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: customers - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: partners - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: contact us - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: urgent enquiries - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: legal - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: privacy policy - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: terms of use - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: copyright policy - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: amia systeme - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: simogga ld - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: kontakt - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: politik - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: datenschutzrichtlinien - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: nutzungsbedingungen - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: urheberrechtspolitik - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: amia systemes - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
> languages-all.js:87 MENU: simogga ld - current lang: null - HIDE
> languages-all.js:88 not in langs - not in all_langs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newearthmartin/weebly-tools/issues/1>.
>



-- 
Del Amor, de la Paz, en el Mundo. - Of Love, of Peace, in the World.

**Comment by Abdelkrim** [comment]
Thanks Martin, Issue is resolved now!
